# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LCDemo

  pod 'LeanCloud'
  pod 'SwiftyUserDefaults'
  pod 'Eureka' , '~>4.3.0'
  pod 'Kingfisher'
  pod 'YPImagePicker'
  pod 'SKPhotoBrowser'
  
end
